### ISSUE TITLE
Is it possible to collect some segmented data sets as new modules of the project?

### ISSUE THREAD

**Issue by zhanghongyong123456** [suhwan-cho/awesome-video-object-segmentation#1]
First of all, thank you for sorting out all the excellent projects about segmentation. Could you please provide some segmented datasets as the new modules(Contents) of this project

**Comment by suhwan-cho** [comment]
Thanks for your suggestion! 
I added some popular datasets that are widely used in VOS as a new content.
Any further suggestions are always welcomed :)

**Comment by zhanghongyong123456** [comment]
> Thanks for your suggestion! I added some popular datasets that are widely used in VOS as a new content. Any further suggestions are always welcomed :)

  Thank you

**Comment by zhanghongyong123456** [comment]
> Thanks for your suggestion! I added some popular datasets that are widely used in VOS as a new content. Any further suggestions are always welcomed :)

I want to know the label list for the ID，Where I can get？
https://youtube-vos.org/dataset/vis/      about  annotations.json   category_id   and  label list   like：  category_id ： 26  is person   label

**Comment by suhwan-cho** [comment]
In VOS, IDs have nothing to do with certain categories.
Each object is annotated by different color just for distinction with other objects.
