### ISSUE TITLE
Request for adding the VOS work "Towards Robust Video Object Segmentation with Adaptive Object Calibration " 

### ISSUE THREAD

**Issue by JerryX1110** [suhwan-cho/awesome-video-object-segmentation#2]
Hi, thanks for maintaining such an awesome repo for VOS-related works. :)

I would like to request for adding our VOS work "Towards Robust Video Object Segmentation with Adaptive Object Calibration" which has been accepted by ACM Multimedia22.

Our project repo is  https://github.com/JerryX1110/Robust-Video-Object-Segmentation
Our preview-version ArXiv paper link is https://arxiv.org/abs/2207.00887

Thanks!

**Comment by suhwan-cho** [comment]
Hi, your request has been completed!
Your paper **AOC: Towards Robust Video Object Segmentation with Adaptive Object Calibration** is on the list now.
Further requests are always welcomed :)

**Comment by JerryX1110** [comment]
Thanks~
