### ISSUE TITLE
Request for adding "Time Does Tell: Self-Supervised Time-Tuning of Dense Image Representations"

### ISSUE THREAD

**Issue by SMSD75** [suhwan-cho/awesome-video-object-segmentation#4]
Hi, 

I would ask you to add this paper that has been accepted in ICCV23. Here is the link : 

Paper : https://arxiv.org/abs/2308.11796
Repo : https://github.com/SMSD75/Timetuning

It is a self-supervised learning method for unsupervised video and image object segmentation.

**Comment by suhwan-cho** [comment]
Hi Mohammadreza,

I have added Timetuning to "Other related papers" section.

Thanks!
