### ISSUE TITLE
Request: Adding READMem to your awesome list

### ISSUE THREAD

**Issue by Vujas-Eteph** [suhwan-cho/awesome-video-object-segmentation#5]
Hi!

I'd like to suggest our paper, presented at BMVC 2023, on improving inter-frame feature diversity in the memory of STM-like architectures. Thought it might be a cool fit for your awesome list.

Here's the paper and our GitHub: [Paper Link](https://papers.bmvc2023.org/0603.pdf) / [GitHub Link](https://github.com/Vujas-Eteph/READMem).

Would be awesome if you could check it out and consider adding it to your list. :)

Cheers!

**Comment by suhwan-cho** [comment]
Hi Stephane,

I have added READMem to the list.

Thanks!

**Comment by Vujas-Eteph** [comment]
Great! Many thanks @suhwan-cho 😄
